### ISSUE TITLE
Deadlock in wait_for_unlock_notify after SQLITE_BUSY

### ISSUE THREAD

**Issue by FiloSottile** [crawshaw/sqlite#6]
I have a program accessing a db with a Pool, and during its operation I lock the database from another process. A couple SQLITE_BUSY errors are returned. Shortly after (but not immediately, like after 3 queries), the library deadlocks in `wait_for_unlock_notify`. It's very reproducible.

This is from a SIGQUIT:

```
goroutine 20 [syscall, 2 minutes]:
github.com/FiloSottile/mostly-harmless/covfefe/vendor/crawshaw.io/sqlite._Cfunc_wait_for_unlock_notify(0x5406710, 0x5406690, 0x0)
	_cgo_gotypes.go:1440 +0x6b
github.com/FiloSottile/mostly-harmless/covfefe/vendor/crawshaw.io/sqlite.(*Stmt).Step.func2(0x5406710, 0x5406690, 0x9)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/vendor/crawshaw.io/sqlite/sqlite.go:492 +0x6e
github.com/FiloSottile/mostly-harmless/covfefe/vendor/crawshaw.io/sqlite.(*Stmt).Step(0xc42034d270, 0x2, 0xef87, 0xef87)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/vendor/crawshaw.io/sqlite/sqlite.go:492 +0x205
github.com/FiloSottile/mostly-harmless/covfefe/vendor/crawshaw.io/sqlite/sqliteutil.exec(0xc42034d270, 0x0, 0xc42029d260, 0x2, 0x2, 0x0, 0x1)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/vendor/crawshaw.io/sqlite/sqliteutil/exec.go:127 +0x396
github.com/FiloSottile/mostly-harmless/covfefe/vendor/crawshaw.io/sqlite/sqliteutil.Exec(0xc4200a4460, 0x4655fb6, 0x72, 0x0, 0xc42029d260, 0x2, 0x2, 0x0, 0x0)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/vendor/crawshaw.io/sqlite/sqliteutil/exec.go:77 +0xe7
github.com/FiloSottile/mostly-harmless/covfefe.(*Covfefe).execSQL.func1(0xc4200a4460, 0x464a967, 0x19)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/db.go:17 +0xa3
github.com/FiloSottile/mostly-harmless/covfefe.Run.func1(0xc420289680, 0x0, 0x0)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/covfefe.go:56 +0x1e3
github.com/FiloSottile/mostly-harmless/covfefe.(*Covfefe).execSQL(0xc420087980, 0x4655fb6, 0x72, 0xc42029d260, 0x2, 0x2, 0xcd2ad7b0084c344a, 0xc420024500)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/db.go:16 +0xf8
github.com/FiloSottile/mostly-harmless/covfefe.(*Covfefe).insertMessage(0xc420087980, 0xc4201be030, 0x0, 0x1)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/db.go:71 +0x613
github.com/FiloSottile/mostly-harmless/covfefe.(*Covfefe).Handle(0xc420087980, 0xc4201be030)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/process.go:154 +0x51d
github.com/FiloSottile/mostly-harmless/covfefe.(*Covfefe).HandleChan(0xc420087980, 0xc420074180)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/process.go:122 +0x57
github.com/FiloSottile/mostly-harmless/covfefe.Run.func2(0xc420087980, 0xc420074180)
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/covfefe.go:74 +0x43
created by github.com/FiloSottile/mostly-harmless/covfefe.Run
	/Users/filippo/src/github.com/FiloSottile/mostly-harmless/covfefe/covfefe.go:73 +0x561
```

(I think) I am using Pool in a fairly straightforward way, and most of the work is done by a single main goroutine. The code is at https://github.com/FiloSottile/mostly-harmless/tree/4a6ff25/covfefe

**Comment by FiloSottile** [comment]
Here's the sequence of events: a few SQLITE_BUSY, then a few SQLITE_DONE, then a SQLITE_LOCKED that deadlocks on pthread_cond_wait. All this happens on the same goroutine, but with a new Pool.Get for each query (as you can see from the PRAGMA query bound to Get).

```
2018/04/08 23:23:28 sqlite3_step(PRAGMA foreign_keys = ON;) = SQLITE_DONE(not an error)
2018/04/08 23:23:28 sqlite3_step(INSERT INTO Users (id, handle, name, bio, first_seen) VALUES (?, ?, ?, ?, ?);) = SQLITE_DONE(not an error)
2018/04/08 23:23:28 sqlite3_step(PRAGMA foreign_keys = ON;) = SQLITE_DONE(not an error)
2018/04/08 23:23:28 sqlite3_step(INSERT INTO Tweets (id, created, user, message) VALUES (?, ?, ?, ?)) = SQLITE_CONSTRAINT
2018/04/08 23:23:51 sqlite3_step(PRAGMA foreign_keys = ON;) = SQLITE_DONE(not an error)
2018/04/08 23:23:51 sqlite3_step(INSERT INTO Messages (json, account) VALUES (?, json_array(?))) = SQLITE_BUSY
2018/04/08 23:23:53 sqlite3_step(PRAGMA foreign_keys = ON;) = SQLITE_DONE(not an error)
2018/04/08 23:23:53 sqlite3_step(INSERT INTO Messages (json, account) VALUES (?, json_array(?))) = SQLITE_BUSY
2018/04/08 23:23:55 sqlite3_step(PRAGMA foreign_keys = ON;) = SQLITE_DONE(not an error)
2018/04/08 23:23:55 sqlite3_step(INSERT INTO Messages (json, account) VALUES (?, json_array(?))) = SQLITE_BUSY
2018/04/08 23:24:59 sqlite3_step(PRAGMA foreign_keys = ON;) = SQLITE_DONE(not an error)
2018/04/08 23:24:59 sqlite3_step(INSERT INTO Messages (json, account) VALUES (?, json_array(?))) = SQLITE_DONE(not an error)
2018/04/08 23:24:59 sqlite3_step(PRAGMA foreign_keys = ON;) = SQLITE_DONE(not an error)
2018/04/08 23:24:59 sqlite3_step(INSERT INTO Tweets (id, created, user, message) VALUES (?, ?, ?, ?)) = SQLITE_DONE(not an error)
2018/04/08 23:24:59 sqlite3_step(PRAGMA foreign_keys = ON;) = SQLITE_DONE(not an error)
2018/04/08 23:24:59 sqlite3_step(INSERT INTO Users (id, handle, name, bio, first_seen) VALUES (?, ?, ?, ?, ?);) = SQLITE_DONE(not an error)
2018/04/08 23:24:59 sqlite3_step(PRAGMA foreign_keys = ON;) = SQLITE_DONE(not an error)
2018/04/08 23:24:59 sqlite3_step(UPDATE Messages SET account = json_insert(account, '$[' || json_array_length(account) || ']', ?) WHERE id = ?;) = SQLITE_LOCKED
sqlite3_unlock_notify
pthread_mutex_lock
pthread_cond_wait
```

I can't reproduce it with a pool size of 1, everything keeps working fine after the SQLITE_BUSY.

**Comment by crawshaw** [comment]
Ouch, thanks. I'll take a look at this tomorrow.

One possibility is that I'm being too imprecise on error matching. Right now the code uses `wait_for_unlock_notify` if it sees `SQLITE_LOCKED`. There may be some condition where competing with another process returns that error instead of `SQLITE_BUSY`, in which case we go into a wait that we don't escape from.

That would be easy to fix, look for the extended error code `SQLITE_LOCKED_SHAREDCACHE`. But I'd like to reproduce it before checking that in.

**Comment by FiloSottile** [comment]
It might be relevant that this is a WAL database.

**Comment by FiloSottile** [comment]
This is on macOS.

**Comment by ksshannon** [comment]
I ran into a similar issue on Ubuntu 16.04, with both `wal` and `delete` journal modes.

**Comment by fasterthanlime** [comment]
Saw this too with a pool of size 2, also having a hard time coming up with a reproducible test case, but I'll attempt to post one as soon as I figure out the conditions.

**Comment by fasterthanlime** [comment]
Merging https://github.com/crawshaw/sqlite/pull/25 closed this issue, but @FiloSottile may want to check if the original issue cannot still be reproduced.
