### ISSUE TITLE
"fatal error: checkptr: unsafe pointer arithmetic" with -race enabled

### ISSUE THREAD

**Issue by AdamSLevy** [crawshaw/sqlite#87]
```
fatal error: checkptr: unsafe pointer arithmetic

goroutine 44 [running]:
runtime.throw(0xbe34a1, 0x23)
	runtime/panic.go:1112 +0x72 fp=0xc00028aed8 sp=0xc00028aea8 pc=0x44b602
runtime.checkptrArithmetic(0x1, 0x0, 0x0, 0x0)
	runtime/checkptr.go:24 +0xce fp=0xc00028af08 sp=0xc00028aed8 pc=0x41e70e
crawshaw.io/sqlite.(*strm).cptr(...)
	crawshaw.io/sqlite@v0.2.5/session.go:514
crawshaw.io/sqlite.(*Session).Changeset.func1(0xc0000100c8, 0xc000077080, 0x0)
	crawshaw.io/sqlite@v0.2.5/session.go:127 +0x9f fp=0xc00028af58 sp=0xc00028af08 pc=0x99a5ef
crawshaw.io/sqlite.(*Session).Changeset(0xc0000100c8, 0xc997c0, 0xc000077050, 0x0, 0x0)
	crawshaw.io/sqlite@v0.2.5/session.go:127 +0x132 fp=0xc00028b080 sp=0xc00028af58 pc=0x98caa2
```

**Comment by AdamSLevy** [comment]
It appears this is related to this change in go1.14: https://golang.google.cn/doc/go1.14#compiler

> This release adds -d=checkptr as a compile-time option for adding instrumentation to check that Go code is following unsafe.Pointer safety rules dynamically. This option is enabled by default (except on Windows) with the -race or -msan flags, and can be disabled with -gcflags=all=-d=checkptr=0. Specifically, -d=checkptr checks the following:
>
>    When converting unsafe.Pointer to *T, the resulting pointer must be aligned appropriately for T.
>    If the result of pointer arithmetic points into a Go heap object, one of the unsafe.Pointer-typed operands must point into the same object.

I'm not familiar enough with the streaming code here to precisely understand what is going on. 

https://github.com/crawshaw/sqlite/blob/251d8861ace668178e83fde7dc196e40480ebab6/session.go#L511-L609

**Comment by AdamSLevy** [comment]
Walked through the streaming code and now I understand how it works. It appears that forcing an int into a uintptr is causing this check to fail here: 

https://github.com/crawshaw/sqlite/blob/251d8861ace668178e83fde7dc196e40480ebab6/session.go#L552

On the gopher slack I got some good suggestions. The main issue to work around here is that we can't pass a go pointer across to SQLite that it hangs onto, which is what is happening in the streaming functions. One way around this is to write an adapter function in C that converts an `int` to a `void*`. This hides this messy conversion from Go entirely. I have some initial code for this that I haven't had much time to work on or test but I'll get to it.

Another way would be to create a C pointer with malloc and use that as the map key. I personally like the C adapter approach better.

**Comment by AdamSLevy** [comment]
@zombiezen Thanks for your suggestion and example on how to address this issue.
